### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by yoseer** [crystoll/projectillithid#2]
Hello, why does it display this when I run the code?
C:\Users\admin\Downloads\projectillithid-master\projectillithid-master\mindreader\recorder.py:27: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  ts = datetime.datetime.utcnow().isoformat()
Raw value: 0, Attention: 0, Meditation: 0
Waves: {}
Raw value: 0, Attention: 0, Meditation: 0
Waves: {}
Raw value: 0, Attention: 0, Meditation: 0
Waves: {}
Raw value: 0, Attention: 0, Meditation: 0
Waves: {}
Raw value: 0, Attention: 0, Meditation: 0
Waves: {}
Raw value: 0, Attention: 0, Meditation: 0
Waves: {}
Raw value: 0, Attention: 0, Meditation: 0
Waves: {}
Raw value: 0, Attention: 0, Meditation: 0
Waves: {}
Raw value: 0, Attention: 0, Meditation: 0
Waves: {}
Raw value: 0, Attention: 0, Meditation: 0
Waves: {}
Raw value: 0, Attention: 0, Meditation: 0
Waves: {}
Raw value: 0, Attention: 0, Meditation: 0
Waves: {}
Raw value: 0, Attention: 0, Meditation: 0
Waves: {}
Raw value: 0, Attention: 0, Meditation: 0
Waves: {}
Raw value: 0, Attention: 0, Meditation: 0
Waves: {}
Raw value: 0, Attention: 0, Meditation: 0
Waves: {}
Raw value: 0, Attention: 0, Meditation: 0
Waves: {}
Raw value: 0, Attention: 0, Meditation: 0
Waves: {}
Raw value: 0, Attention: 0, Meditation: 0
Waves: {}
Raw value: 0, Attention: 0, Meditation: 0
Waves: {}
Raw value: 0, Attention: 0, Meditation: 0
Waves: {}
Raw value: 0, Attention: 0, Meditation: 0
Waves: {}
Raw value: 0, Attention: 0, Meditation: 0
Waves: {}
Raw value: 0, Attention: 0, Meditation: 0
Waves: {}
Raw value: 0, Attention: 0, Meditation: 0
Waves: {}
Raw value: 0, Attention: 0, Meditation: 0
Waves: {}
Raw value: 0, Attention: 0, Meditation: 0
Waves: {}

**Comment by crystoll** [comment]
Hi, which part do you mean? 
Depracation warnings mean there's outdated code accessing datetime library, they are not dangerous however, can be ignored. If one wants to make them go away, either change the code, update libraries (if new versions are available), or adjust logging levels to ignore them.

Getting 0 values from the sensor? Yeah, if I remember correctly, getting any values means software is working, but I get zero values if sensors are not properly attached. If that is the issue, a good way to debug that is to use the other provided software/games that came with the Mindwave, to see if it works and gives brainwaves.

**Comment by yoseer** [comment]
Hi, thank you for your response. I already tested the headset with another software and it works correctly. I'll show the screenshot
![ee](https://github.com/crystoll/projectillithid/assets/159801218/ce572ee1-877e-493d-a6e2-5b3d246fc77a)

**Comment by crystoll** [comment]
Ahh, I see, that narrows it down.
It's a bit hard to remote debug what could be the issue, but some ideas:
- code here is just a thin wrapper on top of the original lib https://github.com/faturita/python-mindwave - converted to Python 3 -  so one option is to try to play with that directly, see if it makes a difference. They have more testing tools.
- I see they have updated it to Python 3 now, which is great news, so I might give it a spin too
- As far as I remember, only time when I was getting 0 values was when my headset sensors were not perfectly in place, also.. for some reason I needed to be patient and wait a bit before data started streaming

But the Faturita git, they have 3 months recent updates now, testing utils for Python 3, so might give it a spin? That kind of outdates my repository a bit, although I might be tempted to try to modernize it now that they are also in Python 3 time :)
